project_id = "creative-moments"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322
major_version = 17

[auth]
site_url = "creativemoments://login-callback"
additional_redirect_urls = ["creativemoments://login-callback", "creativemoments://reset-callback"]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false
